version: "3.5"

services:

  litecoin-client:
    image: litecoin
    container_name: litecoin
    hostname: litecoin
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/opt/graphsense/data
      - ./docker/client.conf:/opt/graphsense/client.conf
    networks:
      - graphsense-net
    ports:
      - 8532:8532
    restart: always

networks:
  graphsense-net:
    name: graphsense-global-net
